### ISSUE TITLE
Type size too small

### ISSUE THREAD

**Issue by drawcard** [rarrindell/faker-xd#1]
Hi, I love this plugin but the type size for each of the options is too small to read (on my Macbook Pro retina screen at least)

![image](https://user-images.githubusercontent.com/1435638/91249331-d224ec80-e795-11ea-874c-e22fe5af6f11.png)

**Comment by rarrindell** [comment]
Agreed, those labels are far too small.  I'll correct this in the next release

**Comment by drawcard** [comment]
Thanks!
